//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAA.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class University
    {
        public int UniversityId { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "University Name is required!")]
        [MinLength(5, ErrorMessage = "University Name is too short!")]
        [MaxLength(100, ErrorMessage = "University Name is too long!")]
        public string UniversityName { get; set; }
    }
}
